name: Handle Contact Form Submission

on:
  repository_dispatch:
    types: [contact-form-submission]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install resend
        
      - name: Send email with Resend
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          node .github/scripts/send-email.js "${{ github.event.client_payload.name }}" "${{ github.event.client_payload.email }}" "${{ github.event.client_payload.subject }}" "${{ github.event.client_payload.message }}"
